# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clickevent',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='shorturl_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortURL'),
        ),
    ]
